### PR TITLE
Fix #168

### LINKED ISSUE #168: Crash in -[FLEXObjectExplorerViewController valueForPropertyAtIndex:]
Relevant part of the crash log:

    Last Exception Backtrace:
    0  __exceptionPreprocess + 0x7c
    1  objc_exception_throw + 0x38
    2  -[NSInvocation getArgument:atIndex:] + 0x200
    3  +[FLEXRuntimeUtility performSelector:onObject:withArguments:error:] + 0xae8
    4  +[FLEXRuntimeUtility valueForProperty:onObject:] + 0x154
    5  -[FLEXObjectExplorerViewController valueForPropertyAtIndex:] + 0x104
    6  -[FLEXObjectExplorerViewController subtitleForRow:inExplorerSection:] + 0x120
    7  -[FLEXObjectExplorerViewController tableView:cellForRowAtIndexPath:] + 0x474

Relevant disassembly (`+[FLEXRuntimeUtility performSelector:onObject:withArguments:error:]` + `0xae8` = `0x6f500`):

    0006f4e4    adrp       x8, #0xcb000      ; @selector(errorWithDomain:code:userInfo:)
    0006f4e8    add        x8, x8, #0x880    ; @selector(getReturnValue:)
    0006f4ec    ldur       x9, [x29, #-0xa0]
    0006f4f0    ldr        x2, [sp, #0x100]
    0006f4f4    ldr        x1, x8
    0006f4f8    mov        x0, x9
    0006f4fc    bl         imp___stubs__objc_msgSend
    0006f500    adrp       x8, #0xc9000

Since `@selector(getReturnValue:)` is in `x1` before the `msgSend`, isn't it crashing in `-[NSInvocation getReturnValue:]`?

I'm not sure what caused it but I've submitted a PR that fixes it somehow.

### PR DESCRIPTION
**Pull request by NSExceptional**
Restructure try-catch branching

### CODE REVIEW

**Comment by NSExceptional** [comment]
`NSGetSizeAndAlignment` simply fails for certain types, there's not a lot we can do here imo. At the very least, this PR should be merged and we could open an issue instead of letting the crash affect users.

**Comment by ryanolsonk** [comment]
I agree if this is the only solution, but moving more things under the try/catch block should be a last resort. If there's a more direct way of fixing the issue, we may be able to succeed in more cases. Is there no consistent repro/test case?

**Comment by NSExceptional** [comment]
Not as far as I cant tell :/ As soon as I find one I'll report it here

File: Classes/Utility/FLEXRuntimeUtility.m [hunk 1]
```diff
@@ -353,66 +353,67 @@ + (id)performSelector:(SEL)selector onObject:(id)object withArguments:(NSArray *
...
-    if (successfullyInvoked) {
-        const char *returnType = [methodSignature methodReturnType];
-        if (returnType[0] == @encode(id)[0] || returnType[0] == @encode(Class)[0]) {
-            __unsafe_unretained id objectReturnedFromMethod = nil;
-            [invocation getReturnValue:&objectReturnedFromMethod];
-            returnObject = objectReturnedFromMethod;
-        } else if (returnType[0] != @encode(void)[0]) {
-            void *returnValue = malloc([methodSignature methodReturnLength]);
-            if (returnValue) {
-                [invocation getReturnValue:returnValue];
```
Comment (NSExceptional) [inline Classes/Utility/FLEXRuntimeUtility.m]: Crash occurs here, because `-[NSInvocation getReturnValue:]` likely `jumps` to `-[NSInvocation getArgument:atIndex:]`, which is where the stack trace says the crash is occurring.

**Comment by NSExceptional** [comment]
Here's a detailed stack trace of the crash inside Snapchat:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: libobjc.A.dylib`objc_exception_throw
    frame #1: CoreFoundation`__NSI1 + 432
    frame #2: CoreFoundation`-[NSInvocation getArgument:atIndex:] + 160
    frame #3: FLEXing.dylib`+[FLEXRuntimeUtility performSelector:onObject:withArguments:error:](self=FLEXRuntimeUtility, _cmd="performSelector:onObject:withArguments:error:", selector="currentMediaScenePath", object=0x00000001d43a8180, arguments=0x0000000000000000, error=0x0000000000000000) at FLEXRuntimeUtility.m:450:17
    frame #4: FLEXing.dylib`+[FLEXRuntimeUtility valueForProperty:onObject:](self=FLEXRuntimeUtility, _cmd="valueForProperty:onObject:", property=0x000000010726ec10, object=0x00000001d43a8180) at FLEXRuntimeUtility.m:189:12
    frame #5: FLEXing.dylib`-[FLEXObjectExplorerViewController valueForPropertyAtIndex:](self=0x000000014b039c00, _cmd="valueForPropertyAtIndex:", index=0) at FLEXObjectExplorerViewController.m:372:17
    frame #6: FLEXing.dylib`-[FLEXObjectExplorerViewController subtitleForRow:inExplorerSection:](self=0x000000014b039c00, _cmd="subtitleForRow:inExplorerSection:", row=0, section=FLEXObjectExplorerSectionProperties) at FLEXObjectExplorerViewController.m:737:108
    frame #7: FLEXing.dylib`-[FLEXObjectExplorerViewController tableView:cellForRowAtIndexPath:](self=0x000000014b039c00, _cmd="tableView:cellForRowAtIndexPath:", tableView=0x000000014a824200, indexPath=0xc000000000000116) at FLEXObjectExplorerViewController.m:977:33
    frame #8: UIKit`-[_UIFilteredDataSource tableView:cellForRowAtIndexPath:] + 100
    frame #9: UIKit`-[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 664
    frame #10: UIKit`-[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 80
    frame #11: UIKit`-[UITableView _updateVisibleCellsNow:isRecursive:] + 2140
    frame #12: UIKit`-[UITableView layoutSubviews] + 140
    ...
    frame #24: UIKit`UIApplicationMain + 208
    frame #25: Snapchat`___lldb_unnamed_symbol30815$$Snapchat + 152
    frame #26: libdyld.dylib`start + 4
```
